services:
  postgres:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=appiecal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres