appiecal:
  spring:
    swagger:
      title: schedule-service
      description: API for interacting with the AH Schedule API (via our systems)
      header-api-keys:
        - name: x-authorization
          key-id: api-key
          description: x-authorization header
    security:
      unauthenticated-routes:
        - /v1/raw-request/*
      authorization:
        jwks:
          refresh-interval: 0 0 0 * * *
          uri: ${JWKS_URL}
  schedule:
    gql:
      url: https://api-gateway.ah.nl/

spring:
  profiles:
    active: local
  application:
    name: schedule-service
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: ${JDBC_URL}