spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appiecal?user=postgres&password=postgres

server:
  port: 8081

appiecal:
  spring:
    security:
      authorization:
        jwks:
          uri: https://auth.klrnbk.nl/application/o/local-test-application/jwks/