appiecal:
  spring:
    swagger:
      title: idp-service
      description: Service for interacting with our and AH's identity provider
      header-api-keys:
        - name: x-authorization
          key-id: api-key
          description: x-authorization header
    security:
      unauthenticated-routes:
        - /v1/entra/start
      authorization:
        jwks:
          refresh-interval: 0 0 0 * * *
          uri: ${JWKS_URL}
  idp:
    encryption-key: ${IDP_ENCRYPTION_KEY}

  azure:
    entra:
      base-authentication-url: https://clp.ah.nl/central-login-page
      azure-entra-url: https://login.microsoftonline.com/
      credentials:
        tenant-id: a6b169f1-592b-4329-8f33-8db8903003c7
        client-id: 4d469dcc-1140-449f-856e-7d2618ec9c36
        scopes: "openid profile offline_access https://dex.ahold.com/.default"
        redirect-uri: http://localhost
        response-type: code
        response-mode: query
        prompt: login

spring:
  profiles:
    active: local
  application:
    name: idp-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${JDBC_URL}