appiecal:
  spring:
    swagger:
      title: idp-service
      description: Service for interacting with our and AH's identity provider
      header-api-keys:
        - name: x-authorization
          key-id: api-key
          description: x-authorization header
  azure:
    entra:
      authentication-url: https://clp.ah.nl/central-login-page?tenant_id=a6b169f1-592b-4329-8f33-8db8903003c7&client_id=4d469dcc-1140-449f-856e-7d2618ec9c36&redirect_uri=http%3A%2F%2Flocalhost&response_type=code&scope=openid+profile+offline_access+https%3A%2F%2Fdex.ahold.com%2F.default&response_mode=query&prompt=login
      azure-entra-url: https://login.microsoftonline.com/
      credentials:
        tenant-id: a6b169f1-592b-4329-8f33-8db8903003c7
        client-id: 4d469dcc-1140-449f-856e-7d2618ec9c36
        scopes: "openid profile offline_access https://dex.ahold.com/.default"

spring:
  application:
    name: schedule-service