name: Build, Release and Deploy Apps

on:
  repository_dispatch:
    types: [version-bumped]
  workflow_dispatch:
    inputs:
      apps_dir:
        description: 'Directory containing the apps'
        type: string
        default: 'src/apps'
        required: false
      apps:
        description: 'Comma-separated list of app names to build and deploy'
        type: string
        required: true

jobs:
  build:
    needs: authenticate-app
    uses: ijsKoud/actions/.github/workflows/generic-kotlin-monorepo-build-release.yaml@main
    with:
      apps_dir: ${{ inputs.apps_dir }}
      apps: ${{ inputs.apps }}
    secrets:
      APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
  deploy:
    needs: build
    uses: ijsKoud/actions/.github/workflows/generic-application-deploy.yaml@main
    with:
      apps: ${{ needs.build.outputs.apps }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
      ARGOCD_SERVER_URL: ${{ secrets.ARGOCD_SERVER_URL }}
      TAILSCALE_CLIENT_ID: ${{ secrets.TAILSCALE_CLIENT_ID }}
      TAILSCALE_CLIENT_SECRET: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
  
