name: Build and Deploy Apps

permissions:
  id-token: write
  contents: read
  packages: write

on:
  repository_dispatch:
    types: [version-bumped]
  workflow_dispatch:
    inputs:
      apps_dir:
        description: 'Directory containing the apps'
        type: string
        default: 'src/apps'
        required: false
      apps:
        description: 'Comma-separated list of app names to build and deploy'
        type: string
        required: true

jobs:
  reuse-workflow:
    uses: ijsKoud/actions/.github/workflows/generic-kotlin-monorepo-build-release.yaml@main
    with:
      apps_dir: ${{ inputs.apps_dir }}
      apps: ${{ inputs.apps }}
