name: Build, Release and Deploy Apps

on:
  repository_dispatch:
    types: [version-bumped]
  workflow_dispatch:
    inputs:
      apps_dir:
        description: 'Directory containing the apps'
        type: string
        default: 'src/apps'
        required: false
      apps:
        description: 'Comma-separated list of app names to build and deploy'
        type: string
        required: true

jobs:
  authenticate-app:
    name: Authenticate GitHub Application
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          skip-token-revoke: true
  build:
    needs: authenticate-app
    uses: ijsKoud/actions/.github/workflows/generic-kotlin-monorepo-build-release.yaml@main
    with:
      apps_dir: ${{ inputs.apps_dir }}
      apps: ${{ inputs.apps }}
      github_app_token: ${{ needs.authenticate-app.outputs.token }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
  deploy:
    needs: build
    uses: ijsKoud/actions/.github/workflows/generic-application-deploy.yaml@main
    with:
      apps: ${{ needs.build.outputs.apps }}
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
      ARGOCD_SERVER_URL: ${{ secrets.ARGOCD_SERVER_URL }}
      TAILSCALE_CLIENT_ID: ${{ secrets.TAILSCALE_CLIENT_ID }}
      TAILSCALE_CLIENT_SECRET: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
  
