name: Manage Phase Secrets

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Update action to perform on PhaseSecret (apply or delete)"
        required: true
        type: choice
        options:
          - apply
          - delete

jobs:
  phase-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
          tags: tag:ci

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply PhaseSecret
        if: ${{ inputs.action == 'apply' }}
        run: |
          kubectl apply -f ./deployment/phase-secret.yaml

      - name: Delete PhaseSecret
        if: ${{ inputs.action == 'delete' }}
        run: |
          kubectl delete -f ./deployment/phase-secret.yaml --ignore-not-found
